export const view: string;
export const editSaid: string;
export const collapse: string;
export const marginBootom: string;
export const selectImage: string;
export const selectMask: string;
export const zoom: string;
export const articleImage: string;
export const selectSong: string;
